sudo: required
services:
  - docker

before_install:
  - docker build -t mehdiichka/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run mehdiichka/react-test npm test -- --coverage

after_success:
  - docker build -t mehdiichka/multi-client ./client
  - docker build -t mehdiichka/multi-server ./server
  - docker build -t mehdiichka/multi-worker ./worker
  - docker build -t mehdiichka/multi-nginx ./nginx
  # Login to dockerhub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images
  - docker push mehdiichka/multi-client
  - docker push mehdiichka/multi-server
  - docker push mehdiichka/multi-worker
  - docker push mehdiichka/multi-nginx
